import type { DashboardData, Job, Monitor, Source } from "./types";
const ago = (hours: number) =>
  new Date(Date.now() - hours * 3600000).toISOString();
export function demoData(): DashboardData {
  const monitors: Monitor[] = [
    {
      id: "m1",
      name: "Full Stack Developer",
      keywords: [
        "full stack developer",
        "full stack engineer",
        "fullstack developer",
        "fullstack engineer",
        "Next.js",
        "React",
        "Node.js",
        "Laravel",
        "PostgreSQL",
      ],
      excludedKeywords: [
        "Senior",
        "Lead",
        "Principal",
        "Staff",
        "Manager",
        "Architect",
      ],
      location: "",
      remoteOnly: false,
      enabled: true,
      createdAt: ago(160),
    },
    {
      id: "m2",
      name: "Software Engineer",
      keywords: [
        "software engineer",
        "application engineer",
        "platform engineer",
        "TypeScript",
        "JavaScript",
        "Python",
        "API",
        "backend",
        "frontend",
      ],
      excludedKeywords: [
        "Senior",
        "Lead",
        "Principal",
        "Staff",
        "Manager",
        "Architect",
      ],
      location: "",
      remoteOnly: false,
      enabled: true,
      createdAt: ago(150),
    },
    {
      id: "m3",
      name: "Software Developer",
      keywords: [
        "software developer",
        "application developer",
        "web developer",
        "frontend developer",
        "backend developer",
        "react developer",
        "node developer",
        "laravel developer",
      ],
      excludedKeywords: [
        "Senior",
        "Lead",
        "Principal",
        "Staff",
        "Manager",
        "Architect",
      ],
      location: "",
      remoteOnly: false,
      enabled: true,
      createdAt: ago(145),
    },
    {
      id: "m4",
      name: "Associate Software Engineer",
      keywords: [
        "associate software engineer",
        "junior software engineer",
        "trainee software engineer",
        "intern software engineer",
      ],
      excludedKeywords: [
        "Senior",
        "Lead",
        "Principal",
        "Staff",
        "Manager",
        "Architect",
      ],
      location: "",
      remoteOnly: false,
      enabled: true,
      createdAt: ago(140),
    },
    {
      id: "m5",
      name: "Frontend React / Next.js",
      keywords: [
        "frontend developer",
        "frontend engineer",
        "front end developer",
        "react developer",
        "next.js developer",
      ],
      excludedKeywords: [
        "Senior",
        "Lead",
        "Principal",
        "Staff",
        "Manager",
        "Architect",
      ],
      location: "",
      remoteOnly: false,
      enabled: true,
      createdAt: ago(135),
    },
    {
      id: "m6",
      name: "Backend Node / Laravel",
      keywords: [
        "backend developer",
        "backend engineer",
        "node developer",
        "laravel developer",
        "api developer",
      ],
      excludedKeywords: [
        "Senior",
        "Lead",
        "Principal",
        "Staff",
        "Manager",
        "Architect",
      ],
      location: "",
      remoteOnly: false,
      enabled: true,
      createdAt: ago(130),
    },
    {
      id: "m7",
      name: "Software roles · Sri Lanka / Colombo / Western",
      keywords: [
        "software engineer",
        "software developer",
        "full stack developer",
        "frontend developer",
        "backend developer",
        "associate software engineer",
        "junior software engineer",
        "react developer",
        "next.js developer",
        "node developer",
        "laravel developer",
      ],
      excludedKeywords: [
        "Senior",
        "Lead",
        "Principal",
        "Staff",
        "Manager",
        "Architect",
      ],
      location: "Sri Lanka",
      remoteOnly: false,
      enabled: true,
      createdAt: ago(120),
    },
    {
      id: "m8",
      name: "Software Engineering · Qatar",
      keywords: [
        "software engineer",
        "software developer",
        "full stack developer",
        "frontend developer",
        "backend developer",
        "web developer",
        "react developer",
        "node developer",
        "application developer",
        "platform engineer",
      ],
      excludedKeywords: [
        "Director",
        "Head of Engineering",
        "Engineering Manager",
      ],
      location: "Qatar",
      remoteOnly: false,
      enabled: true,
      createdAt: ago(110),
    },
    {
      id: "m9",
      name: "Early-career software · Sri Lanka",
      keywords: [
        "associate software engineer",
        "junior software engineer",
        "trainee software engineer",
        "graduate software engineer",
        "entry level software engineer",
        "software engineer intern",
        "intern software engineer",
        "junior developer",
        "trainee developer",
      ],
      excludedKeywords: [
        "Senior",
        "Lead",
        "Principal",
        "Staff",
        "Manager",
        "Architect",
      ],
      location: "Sri Lanka",
      remoteOnly: false,
      enabled: true,
      createdAt: ago(100),
    },
    {
      id: "m10",
      name: "Remote React / Full Stack · Worldwide",
      keywords: [
        "react developer",
        "react engineer",
        "frontend developer",
        "frontend engineer",
        "next.js developer",
        "full stack developer",
        "full stack engineer",
        "node developer",
        "typescript developer",
      ],
      excludedKeywords: [
        "Director",
        "Head of Engineering",
        "Engineering Manager",
      ],
      location: "",
      remoteOnly: true,
      enabled: true,
      createdAt: ago(90),
    },
    {
      id: "m11",
      name: "Early-career software · Qatar",
      keywords: [
        "junior software engineer",
        "associate software engineer",
        "entry level software engineer",
        "graduate software engineer",
        "junior developer",
        "software developer",
        "frontend developer",
        "backend developer",
        "full stack developer",
      ],
      excludedKeywords: [
        "Senior",
        "Lead",
        "Principal",
        "Staff",
        "Manager",
        "Architect",
      ],
      location: "Qatar",
      remoteOnly: false,
      enabled: true,
      createdAt: ago(80),
    },
  ];
  const sources: Source[] = [
    {
      id: "s1",
      name: "Remotive",
      kind: "remotive",
      board: "",
      enabled: true,
      intervalMinutes: 360,
      lastSyncedAt: ago(0.3),
      lastAttemptAt: ago(0.3),
      lastError: null,
      jobCount: 4,
    },
    {
      id: "s2",
      name: "ITPro.lk",
      kind: "itpro",
      board: "",
      enabled: true,
      intervalMinutes: 60,
      lastSyncedAt: ago(0.5),
      lastAttemptAt: ago(0.5),
      lastError: null,
      jobCount: 3,
    },
    {
      id: "s3",
      name: "Dijital Team",
      kind: "lever",
      board: "dijital-team-pty-ltd",
      enabled: true,
      intervalMinutes: 60,
      lastSyncedAt: ago(0.8),
      lastAttemptAt: ago(0.8),
      lastError: null,
      jobCount: 3,
    },
  ];
  const entries = [
    [
      "Senior Frontend Engineer",
      "Linear",
      "Remote · Worldwide",
      "React,TypeScript,Frontend",
      "$140k – $180k",
      "s1",
      "m1",
    ],
    [
      "Full Stack Engineer",
      "Dijital Team",
      "Colombo, Sri Lanka",
      "Next.js,React,PostgreSQL",
      "Not disclosed",
      "s3",
      "m1",
    ],
    [
      "Associate Software Engineer",
      "Notion",
      "Remote · Worldwide",
      "TypeScript,React,API",
      "$80k – $110k",
      "s1",
      "m4",
    ],
    [
      "Backend Engineer, Payments",
      "Stripe",
      "Remote · US",
      "Python,Backend,API",
      "$150k – $200k",
      "s1",
      "m2",
    ],
    [
      "Software Engineer, Platform",
      "Supabase",
      "Remote · Worldwide",
      "TypeScript,PostgreSQL,Go",
      "$120k – $180k",
      "s1",
      "m2",
    ],
    [
      "DevOps Engineer",
      "WSO2",
      "Colombo, Sri Lanka",
      "DevOps,AWS,Kubernetes",
      "Not disclosed",
      "s2",
      "m2",
    ],
    [
      "Frontend Developer",
      "Raycast",
      "Remote · Europe",
      "React,TypeScript,UI",
      "Not disclosed",
      "s1",
      "m5",
    ],
    [
      "Data Engineer",
      "IFS",
      "Colombo, Sri Lanka",
      "Python,SQL,dbt",
      "Not disclosed",
      "s2",
      "m2",
    ],
    [
      "Systems Engineer",
      "Dijital Team",
      "Remote · Sri Lanka",
      "Cloud,Linux,Networks",
      "Not disclosed",
      "s3",
      "m2",
    ],
    [
      "QA Automation Engineer",
      "Dijital Team",
      "Colombo, Sri Lanka",
      "TypeScript,Playwright,QA",
      "Not disclosed",
      "s3",
      "m1",
    ],
  ];
  const jobs: Job[] = entries.map((e, i) => ({
    id: `demo-${i}`,
    externalId: `${i}`,
    title: e[0],
    company: e[1],
    location: e[2],
    tags: e[3].split(","),
    salary: e[4],
    sourceId: e[5],
    sourceName: sources.find((s) => s.id === e[5])!.name,
    matchedMonitors: [e[6]],
    remote: e[2].startsWith("Remote"),
    employmentType: "Full-time",
    description: `This is an illustrative listing for exploring Jobradar, not a verified opening at ${e[1]}.\n\nJoin a collaborative team building thoughtful, reliable software. Work closely with engineering, design, and product to turn complex problems into great experiences.\n\nWhat you’ll do\n• Own meaningful projects from idea to delivery.\n• Build accessible, maintainable products and improve their performance.\n• Collaborate across time zones and share what you learn.\n\nWhat you’ll bring\n• Experience with ${e[3].split(",").join(", ")}.\n• Clear communication and a thoughtful approach to your work.\n\nConnect a real source to collect verified listings with original publication dates and source links.`,
    url: "https://remotive.com",
    publishedAt: ago(i * 6 + 1),
    firstSeenAt: ago(i * 5 + 0.5),
    lastSeenAt: ago(0.3),
    status: i === 4 || i === 8 ? "saved" : i === 7 ? "applied" : "new",
    active: true,
  }));
  sources.forEach((source) => {
    source.jobCount = jobs.filter((job) => job.sourceId === source.id).length;
  });
  return {
    mode: "demo",
    jobs,
    monitors,
    sources,
    authenticated: false,
    user: null,
    runs: sources.map((s, i) => ({
      id: `r${i}`,
      sourceName: s.name,
      startedAt: s.lastSyncedAt!,
      finishedAt: s.lastSyncedAt!,
      status: "success",
      fetched: s.jobCount,
      added: s.jobCount,
      error: null,
    })),
  };
}
